<a href="https://colab.research.google.com/github/priyanka0531/Masterschool/blob/main/Navigating_a_Pandas_Dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Code Exercise 0

This CSV data contains a snapshot of NYC Airbnb listings as of October 2023. Source: [Inside Airbnb](http://insideairbnb.com/get-the-data).


`
http://data.insideairbnb.com/united-states/ny/new-york-city/2023-10-01/visualisations/listings.csv
`


Get started by importing pandas, reading the CSV data into a new dataframe, and inspecting the first few rows.

In [1]:
import pandas as pd
df = pd.read_csv('http://data.insideairbnb.com/united-states/ny/new-york-city/2023-10-01/visualisations/listings.csv')
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,2595,Rental unit in New York · ★4.68 · Studio · 1 b...,2845,Jennifer,Manhattan,Midtown,40.75356,-73.98559,Entire home/apt,240,30,49,2022-06-21,0.29,3,351,0,NaN
1,5121,Rental unit in Brooklyn · ★4.52 · 1 bedroom · ...,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68535,-73.95512,Private room,66,30,50,2019-12-02,0.29,2,151,0,NaN
2,6848,Rental unit in Brooklyn · ★4.58 · 2 bedrooms ·...,15991,Allen & Irina,Brooklyn,Williamsburg,40.70935,-73.95342,Entire home/apt,81,30,191,2023-08-14,1.09,1,79,5,NaN
3,6872,Condo in New York · 1 bedroom · 1 bed · 1 shar...,16104,Kae,Manhattan,East Harlem,40.80107,-73.94255,Private room,65,30,1,2022-06-05,0.06,2,295,0,NaN
4,7064,Loft in Brooklyn · ★4.91 · 1 bedroom · 1 bed ·...,17297,Joelle,Brooklyn,Williamsburg,40.71248,-73.95881,Private room,95,30,13,2022-09-12,0.08,2,26,0,NaN

## Code Exercise 1


Answer the following questions about the dataset:


1.   How many rows and columns are there in the database?
2.   Which columns have null values?
3.   What is the average minimum number of nights?

In [4]:
import pandas as pd
df = pd.read_csv('http://data.insideairbnb.com/united-states/ny/new-york-city/2023-10-01/visualisations/listings.csv')
num_col = df.shape
print(num_col)

(38792, 18)

NYC's [new short-term regulations](https://www.airbnb.com/help/article/868) as of September 2023:


*   Short-term rentals (<30 nights) must register with the city and receive a license, or be an except Class B dwelling (such as hotels)
*   Long-term rentals (>=30 nights) don't need a license

Select and inspect our columns of interest: id, minimum_nights, and license. What values does license take that will help us distiguish listings that are in/out of compliance?

*   Bonus: try .value_counts()

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38792 entries, 0 to 38791
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              38792 non-null  int64
 1   name                            38792 non-null  object
 2   host_id                         38792 non-null  int64
 3   host_name                       38787 non-null  object
 4   neighbourhood_group             38792 non-null  object
 5   neighbourhood                   38792 non-null  object
 6   latitude                        38792 non-null  float64
 7   longitude                       38792 non-null  float64
 8   room_type                       38792 non-null  object
 9   price                           38792 non-null  int64
 10  minimum_nights                  38792 non-null  int64
 11  number_of_reviews               38792 non-null  int64
 12  last_review                     28440 non-null  object
 13  reviews_per_month               28440 non-null  float64
 14  calculated_host_listings_count  38792 non-null  int64
 15  availability_365                38792 non-null  int64
 16  number_of_reviews_ltm           38792 non-null  int64
 17  license                         2939 non-null   object
dtypes: float64(3), int64(8), object(7)
memory usage: 5.3+ MB

In [10]:
#3. What is the average minimum number of nights?
df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm
count,3.879200e+04,3.879200e+04,38792.000000,38792.000000,38792.000000,38792.000000,38792.000000,28440.000000,38792.000000,38792.000000,38792.000000
mean,2.820216e+17,1.558350e+08,40.729379,-73.945829,215.945891,30.639977,25.356285,1.078758,38.581563,148.752629,6.946896
std,3.854980e+17,1.676485e+08,0.056725,0.055115,496.013612,26.633260,55.852480,1.651815,113.306079,142.257519,16.626580
min,2.595000e+03,1.678000e+03,40.500314,-74.251907,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000,0.000000
25%,1.976673e+07,1.643725e+07,40.688790,-73.982820,79.000000,30.000000,0.000000,0.110000,1.000000,0.000000,0.000000
50%,4.542122e+07,7.616643e+07,40.726290,-73.953886,135.000000,30.000000,4.000000,0.410000,1.000000,120.000000,0.000000
75%,7.208503e+17,2.754027e+08,40.762672,-73.926209,225.000000,30.000000,24.000000,1.520000,6.000000,300.000000,5.000000
max,9.927295e+17,5.395985e+08,40.911380,-73.713650,30000.000000,1250.000000,1843.000000,62.820000,602.000000,365.000000,814.000000

In [7]:
df.isnull().sum()

id                                    0
name                                  0
host_id                               0
host_name                             5
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10352
reviews_per_month                 10352
calculated_host_listings_count        0
availability_365                      0
number_of_reviews_ltm                 0
license                           35853
dtype: int64

## Code Exercise 2

We want to find listings that may be out of compliance with the new NYC policy. We need to get a list that we will send to the team to investigate further. Any listings confirmed to be out of compliance will be taken down.

Create new series/columns that identify whether:

*   Whether the listing is short-term (true/false)
*   The listing has no license or marked exempt

Then use them to filter for listings that may be out of compliance (short-term and missing license).

**Hint:** .isnull() and .notnull() to test for null values

In [20]:
short_term = df['minimum_nights']<30
no_license_exempt = ((df['license']=='exempt') | (df['license'].isnull()))
no_license =

In [ ]:
df[short_term & no_license]